updated

diff --git a/.github/workflows/build-packer-image.yml b/.github/workflows/build-packer-image.yml
--- a/.github/workflows/build-packer-image.yml
+++ b/.github/workflows/build-packer-image.yml
@@ -5,7 +5,6 @@ env:
   METADATA_SCRIPT: ${{ vars.METADATA_SCRIPT }}
   METADATA: ${{ vars.METADATA }}
   VM_KEY_PATH: ${{ vars.VM_KEY_PATH }}
-  TEMPLATE_NAME : "Template-$(date +%Y-%m-%d-%H-%M)"
 
 on:
   pull_request:
@@ -29,14 +28,14 @@ jobs:
         with:
           credentials_json: '${{ vars.GOOGLE_APPLICATION_CREDENTIALS }}'
 
-      - name: Run packer
-        run: |
-          cd packer/
-          packer init centos_packer.pkr.hcl
-          packer fmt centos_packer.pkr.hcl
-          echo "$PACKER_VARS" > variables.pkvars.hcl
-          packer validate -var-file="variables.pkvars.hcl" centos_packer.pkr.hcl
-          packer build --force -var-file="variables.pkvars.hcl" centos_packer.pkr.hcl
+      # - name: Run packer
+      #   run: |
+      #     cd packer/
+      #     packer init centos_packer.pkr.hcl
+      #     packer fmt centos_packer.pkr.hcl
+      #     echo "$PACKER_VARS" > variables.pkvars.hcl
+      #     packer validate -var-file="variables.pkvars.hcl" centos_packer.pkr.hcl
+      #     packer build --force -var-file="variables.pkvars.hcl" centos_packer.pkr.hcl
     
 
       - name: Create a new Instance Template version with the latest machine image
@@ -75,8 +74,26 @@ jobs:
             --template=new-template  \
             --region=us-east1
 
-      - name: Start Rolling Update of Instance Group Manager
-        run: |
-          gcloud compute instance-groups managed rolling-action start-update instance-group-manager \
-            --version=template=new-template \
-            --region=us-east1
+      # - name: Start Rolling Update
+      #   run: |
+      #     gcloud compute instance-groups managed rolling-action start-update ${{ vars.MIG_NAME }} \
+      #       --version=template=${{ env.NEW_TEMPLATE_NAME }} \
+      #       --type=proactive \
+      #       --region=${{ vars.REGION }}
+      #   continue-on-error: true
+
+      # - name: Wait for Managed Instance Group Refresh
+      #   id: refresh
+      #   run: |
+      #     sleep 120
+
+      # - name: Monitor Managed Instance Group
+      #   run: |
+      #     output=$(gcloud compute instance-groups managed wait-until ${{ vars.MIG_NAME }} --region=${{ vars.REGION }} --stable)
+      #     if [[ $output == *"Group is stable"* ]]; then
+      #       echo "Managed instance group refresh completed successfully."
+      #       break
+      #     else
+      #       echo "Managed instance group refresh failed."
+      #       exit 1
+      #     fi
